using yQuant.Application.Ports.In;

namespace yQuant.Application.Services;

/*
 * This module involves placing orders automatically based on the trading signals generated by the strategy. This can be done using an API or automated trading software provided by your broker.
 */

internal class OrderService : IOrderUseCase {

}