namespace yQuant.Services;

using yQuant.Ports.Input;

/*
 * This module involves placing orders automatically based on the trading signals generated by the strategy. This can be done using an API or automated trading software provided by your broker.
 */

internal class OrderService : OrderUseCase
{
    public bool RequestOrder(OrderCommand command)
    {
        throw new NotImplementedException();
    }
}