namespace yQuant.Services;

using yQuant.Ports.Input;

/*
 * This module involves placing orders based on the trading signals generated by the strategy. This can be done using an API or automated trading software provided by your broker.
 */

internal class OrderService : OrderFilledUseCase {
    public void OrderFilled(string symbol, decimal price, ushort quantity) {
        throw new NotImplementedException();
    }
}