namespace yQuant.Services;

using yQuant.Ports.Input;
using yQuant.Ports.Output;

/*
 * This module involves placing orders based on the trading signals generated by the strategy. This can be done using an API or automated trading software provided by your broker.
 */

internal class OrderService : OrderPort
{
    public decimal CalcEntryVolume(OrderCommand command)
    {
        throw new NotImplementedException();
    }

    public bool PlaceOrder(OrderCommand command)
    {
        throw new NotImplementedException();
    }
}